TestFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('alumno.urls')),
]

alumno/urls.py
from django.urls import path
from . import views

app_name = 'alumnos'

urlpatterns = [
    path(''                       , views.index , name="index"),
    path('alumnos/'               , views.index , name="alumnos"),
    path('alumnos/read'           , views.read  , name="read"),
    path('alumnos/create'         , views.create, name="create"),
    path('alumnos/edit/<int:id>'  , views.edit  , name="edit"),
    path('alumnos/update/<int:id>', views.update, name="update"),
    path('alumnos/delete/<int:id>', views.delete, name="delete"),
]

alumno/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Alumno(models.Model):  # Modelo creado para ejecutar migraciones
    # Definir los datos de la clase (campos de la tabla)
    # Si no se especifica lo contrario, todos los campos seran requeridos por defecto, es decir NOT NULL
    nombre = models.CharField(max_length=100)
    curso = models.CharField(max_length=100)
    nota = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(20)])
    estado = models.CharField(max_length=20)

    class Meta:
        db_table = "alumno"  # Especificar el nombre de la tabla que se creara en la migración

    def __str__(self):
        return self.nombre + ' ' + self.curso + ' ' + str(self.nota)

alumno/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Alumno

# Create your views here.

def index(request):
    return render(request, "alumno/index.html")

def read(request):
    alumnos = Alumno.objects.all()
    print('alumnos', alumnos)
    return render(request, 'alumno/result.html', {"alumnos":alumnos})

def create(request):
    # crear objeto alumno de la clase alumno
    alumno = Alumno(nombre = request.POST["nombre"],
                    curso = request.POST["curso"],
                    nota = request.POST["nota"],
                    estado = getEstado(request))
    # grabar empleado en la BD
    alumno.save()
    return redirect('/')

def edit(request, id):
    alumno = Alumno.objects.get(id = id)
    arregloAlumno = [alumno.id, alumno.nombre, alumno.curso, alumno.nota]
    data = {'message': "Success", 'alumnos': arregloAlumno}
    return JsonResponse(data)

def update(request, id):
    alumno = Alumno.objects.get(id = id)
    # actualizar datos
    alumno.nombre = request.POST["nombre"]
    alumno.curso = request.POST["curso"]
    alumno.nota = request.POST["nota"]
    alumno.estado = getEstado(request)
    # graba alumno actualizado
    alumno.save()
    return redirect('/')

def delete(request, id):
    alumno = Alumno.objects.get(id = id)
    alumno.delete()
    return redirect('/')

def getEstado(request):
    nota = int(request.POST["nota"])
    if nota >= 14:
        return "APROBADO"
    else:
        return "DESAPROBADO"

alumno/templates/alumno/index.html
{% extends "base.html" %}

{% block titulo %} Lista de Alumnos {% endblock %}

{% block contenido %}
<div class="row">
    <div class="col-12">

        <h4>Listado de Alumnos</h4>
        <h4>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createAlumno" onclick="eliminarNuevo()">
                Crear Alumno
            </button>
        </h4>

        <div class="table-responsive py-2">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre</th>
                        <th>Curso</th>
                        <th>Nota</th>
                        <th>Estado</th>
                        <th colspan="2">Opciones</th>
                    </tr>
                </thead>
                <tbody id="result">
                </tbody>
            </table>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="createAlumno" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <form id="formCreate">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Crear Alumno</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="eliminarNuevo()"></button>
                    </div>
                    <div class="modal-body">

                        <table class="table table-bordered">
                            <thead class="table-dark">
                                <th>Caracteristica</th>
                                <th>Valor</th>
                            </thead>
                            <tbody>
                                {% csrf_token %}
                                <input type="hidden" id="id">
                                <tr>
                                    <td> <label for="nombre">Nombre</label> </td>
                                    <td> <input type="text" class="form-control" id="nombre" placeholder="Ingrese Nombre" required> </td>
                                </tr>
                                <tr>
                                    <td> <label for="curso">Curso</label> </td>
                                    <td> <input type="text" class="form-control" id="curso" placeholder="Ingrese Curso" required> </td>
                                </tr>
                                <tr>
                                    <td> <label for="nota">Nota</label> </td>
                                    <td> <input type="number" class="form-control" id="nota" placeholder="Ingrese Nota" required> </td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" onclick="eliminarNuevo()">Cerrar</button>
                        <button type="submit" class="btn btn-primary" id="create">Crear</button>
                    </div>
                </div>
            </div>
            </form>
        </div>

    </div>
</div>
{% endblock %}

alumno/templates/alumno/result.html
{% for c in alumnos %}
    <tr>
        <td>{{forloop.counter}}</td>
        <td>{{c.nombre}}</td>
        <td>{{c.curso}}</td>
        <td>{{c.nota}}</td>
        <td>{{c.estado}}</td>
        <td><a class="btn btn-success edit" name="{{c.id}}">Editar</a></td>
        <td><a class="btn btn-danger delete" name="{{c.id}}">Eliminar</a></td>
    </tr>
{% endfor %}

alumno/templates/base.html
<!doctype html>
<html lang="es">

<head>
    <!-- Cargamos archivos estaticos -->
    {% load static %}

    <title>{% block titulo %} {% endblock %}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.0.2 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">App Django</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alumnos:index' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'alumnos:alumnos' %}">Alumnos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container py-4">
        {% block contenido %}

        {% endblock %}
    </div>

    <!-- jQuery CDN -->
    <!-- https://releases.jquery.com/ -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"
        integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="{% static '../static/js/jalumno.js' %}"></script>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous">
        </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous">
        </script>
</body>

</html>